baseURL = "https://esquisses.netlify.app/"
languageCode = "fr-fr"
title = "Esquisses"

theme = "cactus"

googleAnalytics = "G-FDLKZ0DGX9"

[params]
  description = "Esquisses est mon carnet de culture des Internets, pensé et crée en 2006, abandonné en 2008 et repris vingt ans après. J'y liste toutes mes découvertes culturelles pour ne pas les oublier!"

  css = ["css/custom.css"]

  mainSectionTitle = "C'est tout chaud!"

  [params.comments]
    enabled = true

disqusShortname = "esquisses" # cactus will use site title if not set

# Main menu which appears below site header.
[[menu.main]]
name = "🏠"
url = "/"
weight = 1

[[menu.main]]
name = "Livres"
url = "/categories/books"
weight = 2


[[menu.main]]
name = "Films"
url = "/categories/movies"
weight = 3


[[menu.main]]
name = "Peintures"
url = "/peintures"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[menu.main]]
name = "A propos"
url = "/a-propos"
weight = 5

